### ISSUE TITLE
Accept a sub-directory for containing the config files

### ISSUE THREAD

**Issue by MahdiBM** [soto-project/soto-codegenerator#78]
Would have been nice if i could have put my files under a directory like `/configs` in the target:
<kbd>
<img width="261" alt="Screenshot 2023-10-04 at 4 05 48 PM" src="https://github.com/soto-project/soto-codegenerator/assets/54685446/0f4e3caa-5122-4594-8116-0df3966d0f73">
</kbd>

**Comment by adam-fowler** [comment]
Think you can currently stick all the files in a subfolder except `endpoints.json`.
